config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'

  resources :messages, except: ['show', 'edit', 'update']

  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :messages
  validates :name, presence: true
  validates :number, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :contact
  validates :to, presence: true
  validates :from, presence: true
  validates :body, presence: true
  before_create :send_sms

  def send_sms
    begin
      response = RestClient::Request.new(
        method: :post,
        url: "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        user: ENV['TWILIO_ACCOUNT_SID'],
        password: ENV['TWILIO_AUTH_TOKEN'],
        payload: { Body: body,
                   To: to,
                   From: from }
      ).execute
    rescue
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      respond_to do |format|
        format.html { redirect_to contacts_path }
        format.js
      end
    else
      render :new
    end
  end

  def show

    @contact = Contact.find(params[:id])
    @messages = @contact.messages
    respond_to do |format|
      format.html {redirect_to contact_path(@contact)}
      format.js
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to messages_path }
      format.js
    end
  end


private
  def contact_params
    params.require(:contact).permit(:name, :number)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to messages_path }
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_path }
      format.js
    end
  end

private
  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.erb
<div class="contact" id="contact_<%= contact.id %>">
  <hr>
  <%= link_to 'X', contact_path(contact), data: {method: 'delete'}, class: 'btn btn-danger btn-xs', remote: true %>

    <%= link_to contact.name, contact_path(contact), remote: true %>

  <div class="box" id="box_for_<%= contact.id %>">

  </div>
</div>

app/views/contacts/_form.html.erb
<div id="contact_form">
  <% if @contact.errors.any? %>
    <h3>ERROR</h3>
    <ul>
      <% @contact.errors.full_message.each do |contact| %>
        <li>
          <%= contact %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <div class="well">
    <%= form_for @contact, remote: true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :number %>
        <%= f.text_field :number, class: 'form-control'%>
      </div>
      <%= f.submit "Save", class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/contacts/_info.html.erb
<div id="info_<%= @contact.id %>">

  <h3>Contact info for <%= @contact.name %></h3>

  <h4>Name: </h4>
  <p><%= @contact.name %></p>

  <h4>Number: </h4>
  <p><%= @contact.number %></p>

  <!--  link_to "Text this contact",  -->
</div>

app/views/contacts/_message.html.erb
<div class="message" id="message_<%= message.id %>">
<hr>
  <%= link_to 'X', message_path(message), data: {method: 'delete'}, class: 'btn btn-danger btn-xs', remote: true %>
  <h4>Sent message:</h4>

  <p>To: <%= message.to %></p>
  <p>From: <%= message.from %></p>
  <p>Message: <%= message.body %> </p>
</div>

app/views/contacts/create.js.erb
$('#contact_form').remove();
$('#contacts').prepend('<%= j render(@contact) %>')
$('#new_contact_btn').show();

app/views/contacts/destroy.js.erb
$('#contact_<%= @contact.id %>').remove();

app/views/contacts/index.html.erb
<%= link_to 'add new contact', new_contact_path, remote: true, class: 'btn btn-info', id: 'new_contact_btn' %>

<div id="contacts">
  <%= render @contacts.reverse %>
</div>

app/views/contacts/new.html.erb
<h3>Here you go javascript haterz</h3>

<%= render 'form' %>

app/views/contacts/new.js.erb
$("#new_contact_btn").hide();
$("#contact_form").remove();
$("#contacts").before('<%= j render "form" %>');

app/views/contacts/show.html.erb
<%= link_to 'send a new message', new_message_path, remote: true, class: 'btn btn-info', id: 'new_btn' %>

<div id="messages">
  <%= render @messages.reverse %>
</div>

app/views/contacts/show.js.erb
// if page.select('#info_ERBTAG @contact.id ERBTAG').any?
$('#box_for_<%= @contact.id %>').toggle();
$('#info_<%= @contact.id %>').remove();
// else
$('#box_for_<%= @contact.id %>').append('<%= j render "info" %>');
// end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Texter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <h1>OMG AAK LMFAO PMP</h1>

    <img src="https://uproxx.files.wordpress.com/2013/09/leslie-knope-textme.gif" alt="leslie" />

    <hr>
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_form.html.erb
<div id="new_form">
  <% if @message.errors.any? %>
    <h3>ERROR ERROR</h3>
    <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <div class="well">
    <%= form_for @message, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :to %>
      <%= f.text_field :to, value: '<%= Contact.find(@message.contact_id).number %>' class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :from %>
      <%= f.text_field :from, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control'%>
    </div>
      <%= f.submit "Send", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/messages/create.js.erb
$('#new_form').remove();
$('#messages').prepend('<%= j render(@message) %>')
$('#new_btn').show();

app/views/messages/destroy.js.erb
$('#message_<%= @message.id %>').remove();

app/views/messages/index.html.erb
<h1>OMG AAK LMFAO PMP</h1>

<img src="https://uproxx.files.wordpress.com/2013/09/leslie-knope-textme.gif" alt="leslie" />

<hr>

<%= link_to 'send a new message', new_message_path, remote: true, class: 'btn btn-info', id: 'new_btn' %>

<div id="messages">
  <%= render @messages.reverse %>
</div>

app/views/messages/new.html.erb
<h1>Send a message</h1>

<%= render "form" %>

app/views/messages/new.js.erb
$("#new_btn").hide();
$('#new_form').remove();
$("#messages").before('<%= j render("form") %>');